language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dockermuch/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dockermuch/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-349846465672"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


  
#DockerReact-env.eba-2yfuyts3.us-east-2.elasticbeanstalk.com
#access_key_id: $AWS_ACCESS_KEY
#secret_access_key: $AWS_SECRET_KEY